Mac build errors
Ok, it didn't give errors about finding the dependancies, so that is
great. There were some other errors, I put the output in
"build_out_1.txt", these are the listed "Issues"

../NitroShare-Mac/nitroshare/src/sharebox/CShareBox.cpp:86: error:
'show' was not declared in this scope

../NitroShare-Mac/nitroshare/src/sharebox/CShareBox.cpp:-1: In member
function 'void CShareBox::Init()':